"""fix tabela appointment

Revision ID: 6edc874d2448
Revises: c4bf7ab3e548
Create Date: 2026-02-20 19:43:56.625655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6edc874d2448'
down_revision: Union[str, Sequence[str], None] = 'c4bf7ab3e548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('vet_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'users', ['vet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'vet_id')
    # ### end Alembic commands ###
