"""fix: column name

Revision ID: c108d86420b1
Revises: 81f0cf8f4732
Create Date: 2026-02-20 14:26:39.465456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c108d86420b1'
down_revision: Union[str, Sequence[str], None] = '81f0cf8f4732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'creted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('creted_at', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
